spring:
  datasource:
    hikari:
      driverClassName: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://127.0.0.1:5432/aposs?PrepareThreshold=0
      username: superuser
      password: qwe123_
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: master-pool
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL91Dialect
      hibernate.format_sql: true
      hibernate.show_slq: false
      hibernate.use_sql_comments: true
      hibernate.physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  ssl:
    enabled: false
    protocol: TLS
    enabled-protocols: TLSv1.2
    key-store-type: PKC12
    key-store: classpath:certs.p12
    key-store-password: qwe123_
kafka:
  bootstrapAddress: localhost:9092
  group: KafkaReplicator
  security: SSL
  keystore:
    path: classpath:key_store.jks
    password: qwe123_
  message:
    topic_1: TOPIC_NAME_1
    topic_2: TOPIC_NAME_2